test:
  adapter: postgresql
  encoding: unicode
  database: advlo_mvp_test
  pool: 5
  username: 
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: advlo_mvp_development
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: advlo_mvp_production
  pool: 5
  username: 
  password:
