development: &default
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: paypal-facilitator_api1.advlo.com
  password: 1406696201
  signature: Ajq945eIQKTFUi-1GcDAbFM3-JWsAqgpz7pcOoeTpCsskTsvcckjmzPS
  sandbox_email_address: paypal-facilitator@advlo.com


test:
  <<: *default

production:
  # Mode can be 'live' or 'sandbox'
  mode: live

  # LIVE CLASSIC API INFO
  app_id: APP-0L453844GN155235K
  username: paypal_api1.advlo.com
  password: 5XLES9AY65HAN48P
  signature: AjHkXon9E6Nuoo0twxHcXVj.GBshAs0lHD5CjH5QD15q0b7Ar33uR03b




