development: &default

  # Credentials for REST APIs
  client_id: Ae4bVRC8PlR2wdsjYgNCUGDPeV94y7CRTmar6oHUPM_-XkPsxaOsQgJ-dq_r
  client_secret: ENjbIBBaTkf18oeGE2GgNYupkjXOO5JKGP7UFtWywRfbpGYzu_OKK_rrveD_

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: paypal-facilitator_api1.advlo.com
  password: 1406696201
  signature: Ajq945eIQKTFUi-1GcDAbFM3-JWsAqgpz7pcOoeTpCsskTsvcckjmzPS
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: paypal-facilitator@advlo.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

test:
  <<: *default

production:
  # Credentials for REST APIs
  client_id: Ae4bVRC8PlR2wdsjYgNCUGDPeV94y7CRTmar6oHUPM_-XkPsxaOsQgJ-dq_r
  client_secret: ENjbIBBaTkf18oeGE2GgNYupkjXOO5JKGP7UFtWywRfbpGYzu_OKK_rrveD_

  # Mode can be 'live' or 'sandbox'
  mode: live

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: paypal-facilitator_api1.advlo.com
  # password: 1406696201
  # signature: Ajq945eIQKTFUi-1GcDAbFM3-JWsAqgpz7pcOoeTpCsskTsvcckjmzPS
  # # # With Certificate
  # # cert_path: "config/cert_key.pem"
  # sandbox_email_address: paypal-facilitator@advlo.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/


  # LIVE CLASSIC API INFO
  username: paypal_api1.advlo.com
  password: 5XLES9AY65HAN48P
  signature: AjHkXon9E6Nuoo0twxHcXVj.GBshAs0lHD5CjH5QD15q0b7Ar33uR03b
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: paypal@advlo.com




