# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbff3816d053411de48dd038976dfefda184ad9a8256c6b5a017d8b28c7a9c5988ff15272de2100f76e2e985f12618a02acb9897c08f6694087c30bd43c1492f

test:
  secret_key_base: a025b6533964cd8abc085a62a36c2082489d62fbb3f6a257cb51464b4576c056e05de4bbcb0a7103e48bdc490c419e12e3e689a083a4f86a9a973e668a50b834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
