module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info alert-block"
      when 'success' then "alert alert-success alert-block"
      when 'error' then "alert alert-error alert-block"
      when 'alert' then "alert alert-error alert-block"
    end
  end	

  # Return array to be used for adventure categories
  def adv_categories
    return ['BIKING', 'CAMPING', 'MOTOR', 'CLIMBING', 'HIKING', 'SNOW', 'WATER', 'OTHER']
  end

  # Return array to be used for MVP - Colorado Regions for scoping adventures by region
  def adv_regions
    return ['Boulder', 'Colorado Springs', 'Denver', 'Fort Collins', 'High Rockies', 'Southern Colorado']
  end

  def active_admin_adv_regions
    return ['all', 'Boulder', 'Colorado Springs', 'Denver', 'Fort Collins', 'High Rockies', 'Southern Colorado']
  end

  def get_continent(country_code)
    continents = {
      "Africa" => [
        "DZ",
        "AO",
        "DZ",
        "AO",
        "BJ",
        "BW",
        "BF",
        "BI",
        "CM",
        "CV",
        "CF",
        "TD",
        "KM",
        "CD",
        "CG",
        "CI",
        "DJ",
        "EG",
        "GQ",
        "ER",
        "ET",
        "GA",
        "GM",
        "GH",
        "GN",
        "GW",
        "KE",
        "LS",
        "LR",
        "LY",
        "MG",
        "MW",
        "ML",
        "MR",
        "MU",
        "YT",
        "MA",
        "MZ",
        "NA",
        "NE",
        "NG",
        "RE",
        "RW",
        "SH",
        "ST",
        "SN",
        "SC",
        "SL",
        "SO",
        "ZA",
        "SD",
        "SZ",
        "TZ",
        "TG",
        "TN",
        "UG",
        "EH",
        "ZM",
        "ZW"
      ],
      "Asia" => [
        "AM",
        "AZ",
        "BH",
        "BD",
        "BT",
        "IO",
        "BN",
        "KH",
        "CN",
        "CX",
        "CC",
        "CY",
        "GE",
        "HK",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IL",
        "JP",
        "JO",
        "KZ",
        "KP",
        "KR",
        "KW",
        "KG",
        "LA",
        "LB",
        "MO",
        "MY",
        "MV",
        "MN",
        "MM",
        "NP",
        "OM",
        "PK",
        "PS",
        "PH",
        "QA",
        "SA",
        "SG",
        "LK",
        "SY",
        "TW",
        "TJ",
        "TH",
        "TL",
        "TR",
        "TM",
        "AE",
        "UZ",
        "VN",
        "YE"
      ],
      "Europe" => [
        "AX",
        "AL",
        "AD",
        "AT",
        "BY",
        "BE",
        "BA",
        "BG",
        "HR",
        "CZ",
        "DK",
        "EE",
        "FO",
        "FI",
        "FR",
        "DE",
        "GI",
        "GR",
        "GG",
        "VA",
        "HU",
        "IS",
        "IE",
        "IM",
        "IT",
        "JE",
        "LV",
        "LI",
        "LT",
        "LU",
        "MK",
        "MT",
        "MD",
        "MC",
        "ME",
        "NL",
        "NO",
        "PL",
        "PT",
        "RO",
        "RU",
        "SM",
        "RS",
        "SK",
        "SI",
        "ES",
        "SJ",
        "SE",
        "CH",
        "UA",
        "GB"
      ],
      "Central America" => [
          "MX",
          "BB",
          "BZ",
          "CR",
          "CU",
          "DM",
          "DO",
          "SV",
          "GD",
          "GT",
          "AI",
          "AG",
          "AW",
          "BS",
          "BM",
          "VG",
          "KY",
          "GP",
          "HT",
          "HN",
          "JM",
          "MQ",
          "MS",
          "AN",
          "NI",
          "PA",
          "PR",
          "BL",
          "KN",
          "LC",
          "MF",
          "PM",
          "VC",
          "TT",
          "TC",
          "VI"
        ],
      "North America" => [
        "US",
        "CA",
        "GL"
      ],
      "South America" => [
        "AR",
        "BO",
        "BR",
        "CL",
        "CO",
        "EC",
        "FK",
        "GF",
        "GY",
        "PY",
        "PE",
        "SR",
        "UY",
        "VE"
      ],
      "Oceania" => [
        "AS",
        "AU",
        "CK",
        "FJ",
        "PF",
        "GU",
        "KI",
        "MH",
        "FM",
        "NR",
        "NC",
        "NZ",
        "NU",
        "NF",
        "MP",
        "PW",
        "PG",
        "PN",
        "WS",
        "SB",
        "TK",
        "TO",
        "TV",
        "UM",
        "VU",
        "WF"
      ]
    }


    # Find the continent and return it
    continents.each do |key,value|
      value.each do |v|
        if v == country_code
          return key
        end
      end
    end

    return "Not Found"

  end

end
